after_image/urls.py
from django.contrib import admin
from django.urls import include, path
from register import views as v

urlpatterns = [
    path('', include('main.urls')), 
    path('admin/', admin.site.urls),
    path("register/", v.register, name = "register"),
    path('', include("django.contrib.auth.urls"))
]

main/urls.py
# urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import go_back
from django.views.static import serve

urlpatterns = [
    path('go-back/', go_back, name='go_back'),
    path('movie/<str:name>', views.month, name='month'),
    path('movie/<str:name>/<str:title>', views.movie, name = "movie"),
    path('movie/<str:name>/<str:title>/discussionposts', views.discussionposts, name = 'discussionposts'),
    path('movie/<str:name>/<str:title>/discussionposts/<int:id>', views.discussionpost, name = 'discussionpost'),
    path("", views.initial_register_or_login, name = "initial_register_or_login"),
    path("home", views.home, name = "home"),
    path("initial_register_or_login", views.initial_register_or_login, name = "initial_register_or_login"),
    path("popular", views.popular, name = "popular"),
    path("profile", views.profile, name = "profile"),
    path("about", views.about, name = "about"),
    path('movie/<str:name>/<str:title>/toggle_watched', views.toggle_watched, name = "toggle_watched"),
    path('movie/<str:name>/<str:title>/discussionposts/<int:id>/toggle_likes', views.toggle_likes, name = "toggle_likes")
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

from datetime import date


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email), **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **kwargs):
        user = self.create_user(email, password=password, **kwargs)
        user.is_admin = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    profile = models.CharField(max_length = 5000, default = "no bio")
    is_admin = models.BooleanField(default = False)
    username = models.CharField(max_length = 50)
    profile_photo = models.URLField(max_length=200, null=True, blank=True)
    
    
    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email
    
    @property
    def is_staff(self):
        return self.is_admin

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True


# Create your models here.
class MovieList(models.Model):
    name = models.CharField(max_length=200)
    archived = models.BooleanField(default = False)
    
    def __str__(self):
        return self.name


class Movie(models.Model):
    movie_list = models.ForeignKey(MovieList, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, unique = True)
    synopsis = models.CharField(max_length=5000)
    watched = models.IntegerField(default = 0)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    release_date = models.IntegerField(default = 2000)
    length = models.IntegerField(default = 120)
    def __str__(self):
        return self.title

class DiscussionPost(models.Model):
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post = models.CharField(max_length = 100000)
    post_likes = models.IntegerField(default = 0)


    def __str__(self):
        return self.post

class Comment(models.Model):
    discussion_post = models.ForeignKey(DiscussionPost, on_delete=models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    comment = models.CharField(max_length = 5000)

    def __str__(self):
        return self.comment

class Discussion_Likes(models.Model):
    discussion_post = models.ForeignKey(DiscussionPost, on_delete = models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete = models.CASCADE)
    liked = models.BooleanField(default = False)

class Movie_Watched(models.Model):
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete = models.CASCADE)
    month = models.ForeignKey(MovieList, on_delete = models.CASCADE)
    date_watched = models.DateField(default = date.today)
    watched = models.BooleanField(default = False)

main/forms.py
from django import forms
from main.models import Movie_Watched
class CreateNewDiscussionPost(forms.Form):
    post = forms.CharField( label="Post", widget=forms.Textarea(attrs={'rows': 10, 'cols': 80, 'placeholder': 'Enter your post here'}), max_length=100000)

class CreateNewComment(forms.Form):
    comment = forms.CharField(label = "Comment", max_length = 10000)

class CreateNewBio(forms.Form):
    bio = forms.CharField(label = "Bio", max_length = 1000)

main/views.py
from django.shortcuts import render, redirect
from .forms import CreateNewDiscussionPost, CreateNewComment, CreateNewBio
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.db.models import Max

# Create your views here.

from django.http import HttpResponse
from .models import MovieList, Movie, DiscussionPost, Comment, MyUser, Movie_Watched, Discussion_Likes

@login_required
def about(response):
    return render(response, "main/about.html")

@login_required
def profile(response):
    user = response.user
    if response.method == "POST":
        form = CreateNewBio(response.POST)
        if form.is_valid():
            user.profile = form.cleaned_data["bio"]
            user.save()
    else:
        form = CreateNewBio()
    return render(response, "main/profile.html",{"user":user, "form":form})

@login_required
def popular(response):
    largest_id = int(MovieList.objects.aggregate(Max('id')).get('id__max',0))
    ls = MovieList.objects.all().get(id = largest_id)
    movie_list = ls.movie_set.all()
    movie_list = sorted(movie_list, key = lambda x: x.watched, reverse = True)
    discussion_post_list = []
    for movie in movie_list:
        for discussion in movie.discussionpost_set.all():
            discussion_post_list.append(discussion)
    
    discussion_post_list = sorted(discussion_post_list, key = lambda x: x.post_likes, reverse = True)
    return render(response, "main/popular.html", {"ls":ls, "movie":movie_list, "discussion":discussion_post_list})


def initial_register_or_login(response):
    return render(response, "main/initial_register_or_login.html")

@login_required
def month(response, name):
    ls = MovieList.objects.get(name = name)
    return render(response, "main/month.html", {"ls":ls})

@login_required
def movie(response, name, title):
    ls = MovieList.objects.all().get(name = name)
    movie = ls.movie_set.get(title = title)
    user = response.user
    try:
        watched = Movie_Watched.objects.get(user = response.user, month = ls, movie = movie)
    except Movie_Watched.DoesNotExist:
        watched = Movie_Watched(user = response.user, movie = movie, month = ls, watched = False)
        watched.save()
    if response.method == "POST":
        form = CreateNewDiscussionPost(response.POST)
        if form.is_valid():
            p = form.cleaned_data["post"]
            t = DiscussionPost(post = p, movie = movie, user = response.user)
            t.save()
    else:
        form = CreateNewDiscussionPost()
    return render(response, "main/" +str(movie.id) + ".html",{"ls":ls,"movie":movie,"watched":watched,"name":name,"title":title, "form":form})

@login_required
def toggle_watched(response, name, title):
    ls = MovieList.objects.all().get(name = name)
    movie = ls.movie_set.get(title = title)
    user = response.user
    try:
        watched = Movie_Watched.objects.get(user = response.user, movie = movie, month = ls)
        watched.watched = not watched.watched
        watched.save()
        if watched.watched == True:
            movie.watched += 1
            movie.save()
        else:
            movie.watched -= 1
            movie.save()
    except Movie_Watched.DoesNotExist:
        watched = Movie_Watched(user = response.user, movie = movie, month = ls, watched = False)
        watched.save()
    
    return redirect('/movie/' + name +  '/' + title)
@login_required
def home(response):
    ls = MovieList.objects.all()
    return render(response, "main/home.html", {"ls":ls})

@login_required
def discussionposts(response, name, title):
    discussionposts = MovieList.objects.all().get(name = name).movie_set.get(title = title).discussionpost_set.all()
    movie = MovieList.objects.all().get(name = name).movie_set.get(title = title)
    return render(response, "main/discussionposts.html", {"discussionposts":discussionposts, "movie":movie})

@login_required
def discussionpost(response, name, title, id):
    discussionpost = MovieList.objects.all().get(name = name).movie_set.get(title = title).discussionpost_set.all().get(id = id)
    movie = MovieList.objects.all().get(name = name).movie_set.get(title = title)
    try:
        liked = Discussion_Likes.objects.get(user = response.user, discussion_post = discussionpost)
    except Discussion_Likes.DoesNotExist:
        liked = Discussion_Likes(user = response.user, discussion_post = discussionpost, liked = False)
        liked.save()
    if response.method == "POST":
        form = CreateNewComment(response.POST)
        if form.is_valid():
            p = form.cleaned_data["comment"]
            t = Comment(comment = p, discussion_post = discussionpost, user = response.user)
            t.save()
    else:
        form = CreateNewComment()

    return render(response, "main/discussionpost.html", {"discussionpost":discussionpost, "form":form, "movie": movie, "name":name, "title":title, "id":id, "liked":liked})

@login_required
def toggle_likes(response, name, title, id):
    discussionpost = MovieList.objects.all().get(name = name).movie_set.get(title = title).discussionpost_set.all().get(id = id)
    try:
        liked = Discussion_Likes.objects.get(user = response.user, discussion_post = discussionpost)
        liked.liked = not liked.liked
        liked.save()
        if liked.liked == True:
            discussionpost.post_likes += 1
            discussionpost.save()
        else:
            discussionpost.post_likes -= 1
            discussionpost.save()
    except Discussion_Likes.DoesNotExist:
        liked = Discussion_Likes(user = response.user, discussion_post = discussionpost, liked = False)
        liked.save()
    id_string = str(id)
    return redirect('/movie/' + name +  '/' + title + '/discussionposts/' + id_string)

def go_back(request):
    return render(request, 'main/movie.html')

main/templates/main/13.html
{%extends 'main/movie.html'%}



{%block content%}
{{block.super}}
{% load static %}
<div class = "text-container">
<div class = "my-title">pretend that you love me.</div>
<div class = "my-description">Joel Haver blends reality and fiction in his 2020 no budget film. It is a deeply personal film that explores his romantic relationships as he wrestles with his own health and the health of his father. Joel Haver is a filmmaker popular on YouTube who is responsible for a number of no budget films and garnered over 1 and a half million subscribers for his sketch comedy. He is a proponent of no budget filmmaking and holds a yearly "Movies That Were Made During The Oscars" event in which his followers make full feature length films in the 3 hour duration of the Oscars. Anti-establishment, inspiring and creative, Joel Haver is a maverick in the filmmaking world.</div>
</div>
<!--* slider cntr -->
<div class="slider">
  <!-- image -->
  <img
    class="slide-image"
    src="{% static 'aftersun-still1.jpeg'%}"
    alt="slide"
  />
     <!-- text overlay -->
     <div class = "slide-description">Description1</div>
  <!-- the count and number of the images -->
  <div class = "numbers">
    <span class="slide-image-number">1</span> of
    <span class="total-image-number">4</span>
  </div>
  <!-- previous btn -->
  <div class="btn backward">
    <span class="material-icons-outlined"> previous</span>
  </div>
  <!-- next btn -->
  <div class="btn forward">
    <span class="material-icons-outlined"> next </span>
  </div>
</div>

<script>
// the variables of the image slider
const image = document.querySelector(".slide-image");
const imageNumber = document.querySelector(".slide-image-number");
const totalImageNumber = document.querySelector(".total-image-number");
const prevBtn = document.querySelector(".backward");
const nextBtn = document.querySelector(".forward");
const slideDescription = document.querySelector(".slide-description");

// the image array
const images = [
"{% static 'pretend1.png'%}",
"{% static 'pretend2.png'%}",
"{% static 'pretend3.png'%}",
"{% static 'pretend4.png'%}",
];

const descriptions = [
  "Landscape",
  "Experimental Use of Aspect Ratio and Colour Grading",
  "Romance",
  "Real Life"
]
// the index of the image on page load
let currentImage = 0;

// the image details that shows when the webpage loads
window.addEventListener("DOMContentLoaded", showImage);

// function to select and change the image details
function showImage() {
  image.src = images[currentImage];
  imageNumber.textContent = currentImage + 1;
  totalImageNumber.textContent = images.length;
  slideDescription.textContent = descriptions[currentImage];
}

// the next button function
nextBtn.addEventListener("click", function () {
  currentImage++;
  if (currentImage > images.length - 1) {
    currentImage = 0;
  }
  showImage(currentImage);
});

// the prev button function
prevBtn.addEventListener("click", function () {
  currentImage--;
  if (currentImage < 0) {
    currentImage = images.length - 1;
  }
  showImage(currentImage);
});




</script>
<style>
  /* heading */
  .my-title {
    font-size: 300%;
    text-align: center;
    font-family: 'Courier New', Courier, monospace
  }
  .my-description{
    font-size: 110%;
    margin-right: 40px;
    font-family: 'Courier New', Courier, monospace
  }
  /* slider container */
  .slider {
    padding: 20px;
    background-color: rgba(255, 255, 255, 0.2);
    position: relative;
    margin: 40px auto;
    max-width: 1000px;

  }
  .text-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
    margin: 5em;
    border: 10px double #000000;
    padding: 1em;
    position: relative;
    background-color: #12507f;
  }

  /* image */
  .slide-image {
    width: auto;
    min-height: 200px;
    height: auto;
    max-height: 100%;
    padding: 10px;
    margin: 0 auto;
    max-width: 100%;
    object-fit: contain;
  }
  
   /* text overlay */
    .slide-description{
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      padding: 20px;
      background-color: rgba(0, 0, 0, 0.5);
      color: #fff;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      text-align: center;
      font-size: 200%;
      font-family: 'Courier New', Courier, monospace
    }
  
  /* paragraph holding the count and number of the images */
  .numbers {
    text-align: center;
  }
  /* prev and next btns */
  .btn.backward {
    position: absolute;
    top: 50%;
    font-size: 80%;
    background-color: rgb(228, 231, 231);
    border: solid 1px rgb(201, 199, 199);
    padding: 5px;
    cursor: pointer;
    left: 0px;
  }

  .btn.forward {
    position: absolute;
    top: 50%;
    font-size: 80%;
    background-color: rgb(228, 231, 231);
    border: solid 1px rgb(201, 199, 199);
    padding: 5px;
    cursor: pointer;
    right: 0px;
  }

  
  </style>

{% endblock %}

main/templates/main/15.html
{%extends 'main/movie.html'%}

{%block content%}
{{block.super}}
<br>
<br>
<h5>Apollo 10 1/2 A Space Age Childhood</h5>
<body>
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Four Columns Template</title>
        <style>
            /* Add styles for the columns and images */
            .columns {
              display: flex;
              flex-wrap: wrap;
            }
            .column {
              flex: 25%;
              padding: 10px;
              box-sizing: border-box;
              
              border: 3px solid #FAF1F3; ;
              background-color: hsl(244, 88%, 10%);
              position: relative;
              padding-bottom: 200px;

            }
            .column img {
              width: 100%;
              height: auto;
              border: 1px solid rgb(147,32,156);
              transition: opacity 0.5s ease;
              /* background-image: linear-gradient(to right, transparent 10%, rgba(0, 0, 0, 0.1) 20%);
              animation: noise 2s infinite linear alternate-reverse; */

            }
            .column:hover img {
              opacity: 0.9;
              background-image: linear-gradient(to right, transparent 10%, rgba(0, 0, 0, 0.1) 20%);
              animation: noise 10s infinite linear alternate-reverse;
            }
            .image-title {
              margin-top: 0;
              font-family: 'Orbitron', sans-serif;
              font-size: 1rem;
              font-weight: bold;
              color: #FAF1F3; 
            }
            .image-description {
              margin-bottom: 0;
              font-family: 'Orbitron', sans-serif;
              font-size: 1rem;
              color: #FAF1F3; 
            }


            @keyframes noise {
            0% {
                transform:  scale(1);
            }
            50% {
                transform:  scale(0.95);
            }
            100% {
                transform:  scale(1);
            }
            }

          </style>
      </head>
      <body>
        <!-- <img src="https://www.whats-on-netflix.com/wp-content/uploads/2016/03/netflixoriginalseries.jpg" alt="Movie Poster"> -->
        <!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/Dzuz5s_Qk-A" frameborder="0" allowfullscreen></iframe> -->
        <div class="columns">
          <div class="column">
            <img src="https://images.unsplash.com/photo-1489549132488-d00b7eee80f1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzN8fHNwYWNlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="Image 1" style="height: 75%">
            <h2 class="image-title">Fact #1</h2>
            <p class="image-description">Jack Black, who voices older Stan, has a personal connection to NASA and the space program. His mother, Judith Love Cohen, helped develop the Abort-Guidance System which ultimately helped get Apollo 13 back to Earth, while she was pregnant with Jack.
            </p>
          </div>
          <div class="column">
            <img src="https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8c3BhY2V8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60" alt="Image 2" style="height: 75%">
            <h2 class="image-title">Fact #2</h2>
            <p class="image-description">Parts of the filming were done in front of a green screen, and everything the characters did not interact with or touch was animated in post-production. Parts of the film, which were shot in live-action, were animated during post-production using a technique similar to the rotoscoping used in Linklater's Waking Life (2001) and A Scanner Darkly (2006).</p>
          </div>
          <div class="column">
            <img src="https://images.unsplash.com/photo-1537420327992-d6e192287183?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c3BhY2V8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60" alt="Image 3" style="height: 75%">
            <h2 class="image-title">Fact #3</h2>
            <p class="image-description">Richard Linklater was planning to create the film in live action but instead decided to go with an animation style influenced by Saturday morning cartoons because of the playful nature of animation. This proved controversial as the Academy of Motion Picture Arts and Sciences denied the movie eligibility for the Animated Feature category for the 2023 Academy Awards in July 2022. After an appeal from the filmmakers and the outcry of much of the industry, the decision was reverted in early January 2023.</p>
          </div>
          <div class="column">
            <img src="https://images.unsplash.com/photo-1505506874110-6a7a69069a08?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8c3BhY2V8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60" alt="Image 4" style="height: 75%">
            <h2 class="image-title">Fact #4</h2>
            <p class="image-description">Prior to the launch of Apollo 10½, Stan is seen reading the July, 1969 edition of Mad Magazine. (Although Apollo 10½ is said to have launched weeks before Apollo 11 on July 16, this would not be an anachronism, as Mad Magazine cover dates were generally 2-3 months later than their actual publication, so the July edition would have been on newsstands as early as May.)</p>
          </div>
        </div>
      </body>
    </html>
</body>
{% endblock %}

main/templates/main/17.html
{%extends 'main/movie.html'%}
{% load static%}
{%block content%}
{{block.super}}
<br>
<br>
<br>
<br>
<style>
    body {
        background: linear-gradient(#002f7a 0%, #d4cc31 95%);
        background-size: 100%;
    }
</style>


<div class="container">
    <div class="content">
        <div class="card glassmorphism mb-4">
            <div class="card mb-3"
                style="background-color: rgba(255, 255, 255, 0.197); backdrop-filter: blur(10px); border: none;">
                <img src="{% static 'redDeer2.jpg'%}"
                    class="card-img-top" alt="InformationPiece 1">
                <div class="card-body">
                    <h5 class="card-title">Directed by Anthony Couture:</h5>
                    <p class="card-text">Born in Red Deer, ALberta, Anthony Couture returned to his hometown to make his first feature film. Red Deer. It premiered at TIFF to postive reception and has its roots in the likes of Michelangelo Antonioni and Wim Wenders. </p>
                </div>
            </div>
        </div>
        

<style>
    .glassmorphism {
        background-color: rgba(255, 255, 255, 0.197);
        border-radius: 20px;
        box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.25);
        backdrop-filter: blur(15px);
        transition: all 0.4s ease;
    }

    .glassmorphism:hover {
        transform: scale(1.03);
    }
    .card-text{
        color: black;
    
    }
    .card-title{
        color:black;
    }
</style>
{% endblock %}

main/templates/main/profile.html
{%extends 'main/base.html'%}

{%block content%}

<div class="jumbotron">
    <div class="container">
        <h3>Profile</h3><br> </br>
        <div style = "text-align: center;">
            <p1 style="font-size: 20px; color: black;" >{{ user.profile }}<p1>
            <br></br>
        </div>

        <div style="text-align: center;">
            <form method="post" action="#">
                {% csrf_token %}
                <p1 style = "color: black;">{{ form }}</p1>
                <button type="submit" name="save" class="btn btn-primary"> Create New</button>
            </form>
        </div>
        <br></br>

        <h4 >Liked Discussion Posts</h5>

        {% for liked in user.discussion_likes_set.all %}
            {%if liked.liked == True%}
            <a style="font-size: 16px;" href="{%url 'discussionpost' liked.discussion_post.movie.movie_list.name liked.discussion_post.movie.title liked.discussion_post.id%}">
                    <div style="text-align: center;">
                        By: {{liked.discussion_post.user}}
                        <li>{{liked.discussion_post.post}}</li>
                        {{liked.discussion_post.post_likes}} Likes
                        <br></br>
                    </div>
                </a>
            {%endif%}
        {%endfor%}
        <br></br>


        <h4>Watched Movies</h4>
        <div class="container" id="movie-container">
            <div class="row movie-grid">
            {% for watched in user.movie_watched_set.all %}
                {%if watched.watched == True%}
                    <div class=" col-lg-3 movie-card">
                        <div class="card">
                            <a href="{% url 'movie' watched.month watched.movie.title %}">
                                <p>{{ watched.movie.watched }} Watches</p>
                                <img src="{{ watched.movie.image.url }}" alt="{{ watched.movie.title }}" 
                                style="height: 400px; width: 250px; margin-bottom: 2px; margin-top: 2px;">
                                <p>{{ watched.movie.title }}</p>
                            </a>
                        </div>
                    </div>
                {%endif%}
            {%endfor%}
            </div>
        </div>
    </div>
</div>         
<style>
    .movie-card {
        border-radius: 20px;
        border: none;
        box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 15px 0px;
        padding-bottom: 10px;
        padding-top: 10px;
        margin-bottom: 25px;
    }

    .movie-card:hover {
        transform: scale(1.03);
    }

    .card {
        border: none;
        background: transparent;
        transition: transform 0.3s ease-in-out;
    }

    .card:hover {
        transform: scale(1.03);
    }

    h3 {
        font-family: 'Sora', sans-serif;
        font-size: 4em;
        font-weight: 1000;
        text-shadow: 1px 3px black;
        text-align: center;
        color: black;
    }
    
    h4 {
        font-family: 'Sora', sans-serif;
        font-size: 2em;
        font-weight: 100;
        text-shadow: 1px 2px black;
        text-align: center;
        color: black;
    }


    p {
        font-family: sans-serif;
        font-size: 20px;
        text-align: center;
        color: black;
    }

    a {
        font-size: 20px;
        color: black;
    }
    a:hover {
        color: black;
    }
</style>

{%endblock%}